[2025-04-03T08:58:15.273+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-03T08:58:15.351+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag_name.fetch_xcom_data manual__2025-04-03T08:57:52.961713+00:00 [queued]>
[2025-04-03T08:58:15.377+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag_name.fetch_xcom_data manual__2025-04-03T08:57:52.961713+00:00 [queued]>
[2025-04-03T08:58:15.378+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-03T08:58:15.407+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): fetch_xcom_data> on 2025-04-03 08:57:52.961713+00:00
[2025-04-03T08:58:15.438+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=224) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-03T08:58:15.441+0000] {standard_task_runner.py:72} INFO - Started process 226 to run task
[2025-04-03T08:58:15.447+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag_name', 'fetch_xcom_data', 'manual__2025-04-03T08:57:52.961713+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/intermediaire_table.py', '--cfg-path', '/tmp/tmp84onrwf8']
[2025-04-03T08:58:15.450+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask fetch_xcom_data
[2025-04-03T08:58:15.536+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag_name.fetch_xcom_data manual__2025-04-03T08:57:52.961713+00:00 [running]> on host d6badcb20287
[2025-04-03T08:58:15.672+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag_name' AIRFLOW_CTX_TASK_ID='fetch_xcom_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T08:57:52.961713+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-03T08:57:52.961713+00:00'
[2025-04-03T08:58:15.675+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-03T08:58:15.676+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-03T08:58:15.676+0000] {logging_mixin.py:190} INFO - Current task name:fetch_xcom_data state:running start_date:2025-04-03 08:58:15.352098+00:00
[2025-04-03T08:58:15.677+0000] {logging_mixin.py:190} INFO - Dag name:my_dag_name and current dag run status:running
[2025-04-03T08:58:15.677+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-03T08:58:15.678+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/intermediaire_table.py", line 89, in fetch_xcom_data
    result1, result2 = fetch_xcom_data.xcom_pull(task_ids='call_external_function')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_TaskDecorator' object has no attribute 'xcom_pull'
[2025-04-03T08:58:15.696+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-03T08:58:15.697+0000] {logging_mixin.py:190} INFO - Task start:2025-04-03 08:58:15.352098+00:00 end:2025-04-03 08:58:15.695974+00:00 duration:0.343876
[2025-04-03T08:58:15.697+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): fetch_xcom_data> dag:<DAG: my_dag_name> dagrun:<DagRun my_dag_name @ 2025-04-03 08:57:52.961713+00:00: manual__2025-04-03T08:57:52.961713+00:00, state:running, queued_at: 2025-04-03 08:57:52.983269+00:00. externally triggered: True>
[2025-04-03T08:58:15.698+0000] {logging_mixin.py:190} INFO - Failure caused by '_TaskDecorator' object has no attribute 'xcom_pull'
[2025-04-03T08:58:15.698+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=my_dag_name, task_id=fetch_xcom_data, run_id=manual__2025-04-03T08:57:52.961713+00:00, execution_date=20250403T085752, start_date=20250403T085815, end_date=20250403T085815
[2025-04-03T08:58:15.740+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-03T08:58:15.741+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task fetch_xcom_data ('_TaskDecorator' object has no attribute 'xcom_pull'; 226)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/intermediaire_table.py", line 89, in fetch_xcom_data
    result1, result2 = fetch_xcom_data.xcom_pull(task_ids='call_external_function')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_TaskDecorator' object has no attribute 'xcom_pull'
[2025-04-03T08:58:15.784+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-03T08:58:15.813+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-03T08:58:15.815+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
